WebStore/WebStore.UI/Areas/Admin/Controllers/CouponController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebStore.UI.Data;
using WebStore.UI.Models;
using WebStore.UI.Utility;

namespace WebStore.UI.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetail.ManagerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;

        [BindProperty]
        public Coupon Coupon { get; set; }

        public CouponController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
            Coupon = new Coupon();
        }

        public async Task<IActionResult> Index()
        {
            return View(await _applicationDbContext.Coupon.ToListAsync());
        }

        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateConfirmed()
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] picture1 = null;
                    using (var fileStream1 = files[0].OpenReadStream())
                    {
                        using (var memoryStream1 = new MemoryStream())
                        {
                            fileStream1.CopyTo(memoryStream1);
                            picture1 = memoryStream1.ToArray();
                        }
                    }
                    Coupon.Picture = picture1;
                }
                _applicationDbContext.Coupon.Add(Coupon);
                await _applicationDbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Coupon);
        }

        //GET - EDIT
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Coupon = await _applicationDbContext.Coupon.SingleOrDefaultAsync(i => i.Id == id);

            if (Coupon == null)
                return NotFound();

            return View(Coupon);
        }

        //POST - EDIT
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var couponFromDb = await _applicationDbContext.Coupon.Where(i => i.Id == id).FirstOrDefaultAsync();

            if (ModelState.IsValid)
            {
                //Work on the image
                var files = HttpContext.Request.Form.Files;

                if (files.Count > 0)
                {
                    byte[] picture1 = null;
                    using (var fileStream1 = files[0].OpenReadStream())
                    {
                        using (var memoryStream1 = new MemoryStream())
                        {
                            fileStream1.CopyTo(memoryStream1);
                            picture1 = memoryStream1.ToArray();
                        }
                    }
                    couponFromDb.Picture = picture1;
                }
                couponFromDb.Name = Coupon.Name;
                couponFromDb.CouponType = Coupon.CouponType;
                couponFromDb.Discount = Coupon.Discount;
                couponFromDb.MinimumAmount = Coupon.MinimumAmount;
                couponFromDb.IsActive = Coupon.IsActive;

                await _applicationDbContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            Coupon.Picture = couponFromDb.Picture;
            return View(Coupon);
        }

        //GET - DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            Coupon = await _applicationDbContext.Coupon.SingleOrDefaultAsync(i => i.Id == id);

            if (Coupon == null)
                return NotFound();

            return View(Coupon);
        }

        //GET - DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Coupon = await _applicationDbContext.Coupon.SingleOrDefaultAsync(i => i.Id == id);

            if (Coupon == null)
                return NotFound();

            return View(Coupon);
        }

        //POST - DELETE
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
                return NotFound();
            Coupon coupon = await _applicationDbContext.Coupon.FindAsync(id);
            if (coupon == null)
                return NotFound();
            _applicationDbContext.Coupon.Remove(coupon);
            await _applicationDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebStore/WebStore.UI/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebStore.UI.Data;
using WebStore.UI.Utility;

namespace WebStore.UI.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetail.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public UserController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _applicationDbContext.ApplicationUser.Where(i => i.Id != claim.Value).ToListAsync());
        }

        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
                return NotFound();

            var applicationUser = await _applicationDbContext.ApplicationUser.FirstOrDefaultAsync(i => i.Id == id);

            if (applicationUser == null)
                return NotFound();

            applicationUser.LockoutEnd = DateTime.Now.AddYears(100);

            await _applicationDbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
                return NotFound();

            var applicationUser = await _applicationDbContext.ApplicationUser.FirstOrDefaultAsync(i => i.Id == id);

            if (applicationUser == null)
                return NotFound();

            applicationUser.LockoutEnd = DateTime.Now;

            await _applicationDbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

WebStore/WebStore.UI/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

WebStore/WebStore.UI/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp; Create New</a>
</p>

WebStore/WebStore.UI/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model"
               value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

WebStore/WebStore.UI/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <a class="btn btn-info form-control" asp-action="Edit" asp-route-id="@Model">Edit</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

WebStore/WebStore.UI/Views/Shared/_EditAndBackToListButton.cshtml
@model  int
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model"
               value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

WebStore/WebStore.UI/Views/Shared/_IndividualOrderDetails.cshtml
@model OrderDetailsViewModel

<form asp-action="OrderPickup" asp-controller="Order" asp-route-orderId="@Model.OrderHeader.Id" method="post">
    <!--Left part-->
    <div class="container row border ml-1 backgroundWhiteBorder10Padding" style="width:100%">
        <div class="col-lg-8 col-12" style="border-right: 1px solid #bbb9b9">
            <br />
            <input type="hidden" asp-for="OrderHeader.Id" />

            <div class="form-group row">
                <div class="col-3">
                    <label>Name</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.PickupName" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.ApplicationUser.Email"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.ApplicationUser.PhoneNumber"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.OrderTotal"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.OrderDate "></label>
                </div>
                <div class="col-9">
                    <input value="@Model.OrderHeader.PickUpTime.ToShortDateString()
                           @Model.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.Comments"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>
        <!--Right area-->
        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">Order ID: </span>
                <span class="badge badge-secondary badge-pill">@Model.OrderHeader.Id</span>
            </h4>
            <ul class="list-group mb-3">
                @foreach (var details in Model.OrderDetails)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            <h6 class="my-0">@details.Name</h6>
                            <small class="text-muted">Quantity: @details.Count</small>
                        </div>
                        <span class="text-muted">
                            @(details.Price * details.Count)
                        </span>
                    </li>
                }
                @if (Model.OrderHeader.CouponCode != null)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div class="text-success">
                            <h6 class="my-0">Promo Code</h6>
                            <small>@Model.OrderHeader.CouponCode</small>
                        </div>
                        <span class="table-success">
                            @(Model.OrderHeader.OrderTotalOriginal - Model.OrderHeader.OrderTotal)
                        </span>
                    </li>
                }
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <span class="text-info">Total (UAH)</span>
                    <strong class="text-info">@Model.OrderHeader.OrderTotal.ToString("c")</strong>
                </li>
            </ul>

            @if (Model.OrderHeader.Status.Equals(StaticDetail.StatusReady)
                                           && (User.IsInRole(StaticDetail.ManagerUser)
                                           || User.IsInRole(StaticDetail.FrontDeskUser)))
            {
                <button type="submit" class="btn btn-success form-control">
                    <i class="far fa-thumbs-up"> Confirm Pickup</i>
                </button>
            }
            else
            {
                <button type="submit" disabled class="btn btn-info form-control">
                    @Model.OrderHeader.Status
                </button>
            }
        </div>
    </div>
</form>

WebStore/WebStore.UI/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CHA SHI FU</title>
    <!--===============================================================================================-->
    <!--LOGO-->
    <link rel="icon" type="image/png" href="/images/icons/favicon.png" />
    <!--===============================================================================================-->
    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-timepicker/jquery.timepicker.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/css/MainPage.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background" id="top">
    <!-- Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="font-family: 'Russo One', sans-serif;">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/icons/tealife-01.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                CHA SHI FU
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle Navigation">
                Menu <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">

                    @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu" arial-labelledby="navDropdown">
                            <a class="dropdown-item" href="#">Sub-Link 1</a>
                            <a class="dropdown-item" href="#">Sub-Link 2</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Sub-Link 3</a>
                        </div>
                    </li>*@
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#link1">ПУЭР</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#link2">Красный Чай</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#link3">Зеленый Чай</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#link4">Белый Чай</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#link5">Посуда</a></li>

                    @*<form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0">Search</button>
                    </form>*@

                </ul>
            </div>
        </div>
    </nav>
    <!-- Header -->
    <header class="masthead">
        <div class="container">
            <div class="intro-text">

            </div>
        </div>
    </header>
    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/icons/tealife-01.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                        TeaWebShop
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            @if (User.IsInRole(StaticDetail.ManagerUser))
                            {
                                <li class="nav-item dropdown text-white-50">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink"
                                       role="button" data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">
                                        Content Management
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category"
                                           asp-action="Index">
                                            Category
                                        </a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="SubCategory"
                                           asp-action="Index">Sub Category</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="MenuItem"
                                           asp-action="Index">MenuItem</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Coupon"
                                           asp-action="Index">Coupons</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User"
                                           asp-action="Index">Users</a>
                                    </div>
                                </li>
                            }

                            @if (User.IsInRole(StaticDetail.ManagerUser)
                              || User.IsInRole(StaticDetail.CustomerEndUser)
                              || User.IsInRole(StaticDetail.FrontDeskUser)
                              || User.IsInRole(StaticDetail.SupplyUser))
                            {
                                <li class="nav-item">
                                    <a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory" class="nav-link">
                                        Order History
                                    </a>
                                </li>
                            }

                            @if (User.IsInRole(StaticDetail.SupplyUser) ||
                            User.IsInRole(StaticDetail.ManagerUser) ||
                            User.IsInRole(StaticDetail.FrontDeskUser))
                            {
                                <li class="nav-item dropdown text-white-50">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropDown"
                                       role="button" data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">
                                        Order
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                        @if (User.IsInRole(StaticDetail.SupplyUser) || User.IsInRole(StaticDetail.ManagerUser))
                                        {
                                            <a class="dropdown-item" asp-area="Customer" asp-controller="Order"
                                               asp-action="ManageOrder">
                                                Manage Order
                                            </a>
                                        }
                                        @if (User.IsInRole(StaticDetail.FrontDeskUser) || User.IsInRole(StaticDetail.ManagerUser))
                                        {
                                            <a class="dropdown-item" asp-area="Customer" asp-controller="Order"
                                               asp-action="OrderPickup">Order Pickup</a>
                                        }
                                    </div>
                                </li>
                            }

                            @if (HttpContextAccessor.HttpContext.Session.GetInt32(StaticDetail.startSessionShoppingCartCount) != null)
                            {
                                <li style="color:white">
                                    <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                        @{
                                            var count = HttpContextAccessor.HttpContext.Session.GetInt32(StaticDetail.startSessionShoppingCartCount);
                                        }
                                        <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                    </a>
                                </li>
                            }
                            else
                            {
                                <li style="color:white">
                                    <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                        <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color:#343a40;">
        <div class="container">
            &copy; 2020 - WebStore.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.tiny.cloud/1/4lzo1w56ky026uhmcekj52s4cv7gdukwj26v85i16005opjl/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/popper.js/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/js/navbar-shrinker.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebStore/WebStore.UI/Views/Shared/_OrderStatus.cshtml
@model string

<div style="width:100%">
    @if (Model == StaticDetail.StatusSubmitted)
    {
        <img src="~/images/OrderPlaced.png" width="100%" />
    }
    @if (Model == StaticDetail.StatusInProcess)
    {
        <img src="~/images/InKitchen.png" width="100%" />
    }
    @if (Model == StaticDetail.StatusReady)
    {
        <img src="~/images/ReadyForPickup.png" width="100%" />
    }
    @if (Model == StaticDetail.StatusCompleted)
    {
        <img src="~/images/completed.png" width="100%" />
    }
</div> 

WebStore/WebStore.UI/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

WebStore/WebStore.UI/Views/Shared/_TableButtonPartial.cshtml
@model  int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

WebStore/WebStore.UI/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>

@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) list-shop">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>

        @foreach (var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.PictureUri" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:18px;color:maroon;">@item.Name</label>
                                @if (item.KindOfFlavour == "0")
                                {
                                    <span style="color: saddlebrown">
                                        <i class="fas fa-mortar-pestle"></i>
                                    </span>
                                }
                                @if (item.KindOfFlavour == "1")
                                {
                                    <span style="color: green;">
                                        <i class="fas fa-apple-alt"></i>
                                    </span>
                                }
                                @if (item.KindOfFlavour == "2")
                                {
                                    <span style="color: sandybrown">
                                        <i class="fas fa-cookie"></i>
                                    </span>
                                }
                                @if (item.KindOfFlavour == "3")
                                {
                                    <span style="color: yellowgreen;">
                                        <i class="fas fa-lemon"></i>
                                    </span>
                                }
                                @if (item.KindOfFlavour == "4")
                                {
                                    <span style="color: forestgreen;">
                                        <i class="fas fa-spa"></i>
                                    </span>
                                }
                            </div>
                            <div class="col-4 text-right" style="color:#423f3f">
                                <h4>@item.Price.ToString("c")</h4>
                            </div>
                        </div>


                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">
                                Details
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="p-4"></div>

    </div>
}